language: python

python:
  - "2.7"

branches:
  only:
    - master
    - progress

install: "pip install -r requirements.txt"

script: echo foo

before_script: echo 'Hello'
after_script: echo 'Bye'

notifications:
  email:
    recipients:
      - bibacb.fb@gmail.com
      
    on_success: [always]
    on_failure: [always]
